# -*- coding: utf-8 -*-
"""Que2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2PhKx2jWdDA16_YGOPSJameZjU3EW8X
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

data = pd.read_csv("Que2.csv")

new_data = data.replace('?', np.nan)
new_data.dropna(inplace = True)

# Creating Linear Regression Model
reg = linear_model.LinearRegression()
X = new_data[['symboling','normalized_losses','wheel-base','length','width','height','curb-weight','engine-size','bore','stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg']]
y = new_data['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)
  
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)
# print(y_pred)
print(reg.score(X_test, y_test))

